[package]
name = "mpc-deck"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"

[dependencies]
evdev-rs = "0.6"
log = "0.4"
pretty_env_logger = "0.4"

[dependencies.clap]
version = "4.0"
features = ["derive"]
